# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import asyncio
import json
import logging
import os
from abc import ABC
from collections.abc import AsyncGenerator, Mapping
from math import sqrt
import numpy as np

from vllm import CompletionOutput, RequestOutput
from vllm.engine.protocol import EngineClient
from vllm.inputs import EngineInput
from vllm.lora.request import LoRARequest
from vllm.renderers import BaseRenderer
from vllm.sampling_params import BeamSearchParams, SamplingParams
from vllm.utils import random_uuid
from vllm.utils.async_utils import collect_from_async_generator

from vllm.entrypoints.generate.beam_search.utils import BeamSearchSequence, create_sort_beams_key_function
from beam_star.beam_star_rd_instrumentation import RDLedger
from beam_star.stats_utils import GlobalRunningStats
from vllm.logger import init_logger

logger = init_logger(__name__)
DEBUG = os.getenv("DEBUG", "0") == "1"
BEAM_STAR_LOG_DIR = "logs/beam_star_debug"
raw = os.getenv("EXPLORATION_TOKENS", "-1").strip()
is_global_stats = os.getenv("GLOBAL_STATS", "1") == "1"

if raw == "-1" or raw == "":
    _EXPLORATION_TOKENS = {-1}
else:
    _EXPLORATION_TOKENS = {
        int(x.strip())
        for x in raw.split(",")
        if x.strip() != ""
    }

async def beam_search(
    self,
    prompt: EngineInput,
    request_id: str,
    params: BeamSearchParams,
    lora_request: LoRARequest | None = None,
    trace_headers: Mapping[str, str] | None = None,
) -> AsyncGenerator[RequestOutput, None]:
    beam_width = params.beam_width
    max_tokens = params.max_tokens
    ignore_eos = params.ignore_eos
    temperature = params.temperature
    length_penalty = params.length_penalty
    include_stop_str_in_output = params.include_stop_str_in_output
    cum_threshold = getattr(params, 'cum_logprob_threshold', -10.0)    
    ledger = RDLedger(delta_budget_nats=float("inf"))    
    tokenizer = self.renderer.get_tokenizer()
    eos_token_id = tokenizer.eos_token_id
    sort_beams_key = create_sort_beams_key_function(eos_token_id, length_penalty)

    if prompt["type"] == "embeds":
        raise NotImplementedError("Embedding prompt not supported for beam search")

    # Extract prompt tokens and text based on model type
    decoder_prompt = (
        prompt if prompt["type"] != "enc_dec" else prompt["decoder_prompt"]
    )
    prompt_text = decoder_prompt.get("prompt")
    prompt_token_ids = decoder_prompt["prompt_token_ids"]

    tokenized_length = len(prompt_token_ids)

    logprobs_num = 2 * beam_width
    sampling_params = SamplingParams(
        logprobs=logprobs_num,
        max_tokens=1,
        temperature=temperature,
    )
    all_beams = [
        BeamSearchSequence(
            orig_prompt=prompt,
            tokens=prompt_token_ids,
            cum_logprob=0,
            logprobs=[],
            lora_request=lora_request,
        )
    ]
    completed = []

    if DEBUG:
        # Open JSONL log for this request (one line per token + final summary)
        os.makedirs(BEAM_STAR_LOG_DIR, exist_ok=True)
        log_path = os.path.join(BEAM_STAR_LOG_DIR, f"beam_star.jsonl")
        log_f = open(log_path, "a", encoding="utf-8")

    for token in range(max_tokens):
        tasks = []
        request_id_batch = f"{request_id}-{random_uuid()}"

        for i, beam in enumerate(all_beams):
            prompt_item = beam.get_prompt()
            lora_request_item = beam.lora_request
            request_id_item = f"{request_id_batch}-beam-{i}"
            task = asyncio.create_task(
                collect_from_async_generator(
                    self.engine_client.generate(
                        prompt_item,
                        sampling_params,
                        request_id_item,
                        lora_request=lora_request_item,
                        trace_headers=trace_headers,
                    )
                )
            )
            tasks.append(task)

        output = [x[0] for x in await asyncio.gather(*tasks)]

        new_beams = []
        # Store all new tokens generated by beam
        all_beams_token_id = []
        # Store the cumulative probability of all tokens
        # generated by beam search
        all_beams_logprob = []
        # Iterate through all beam inference results
        for i, result in enumerate(output):
            current_beam = all_beams[i]

            # check for error finish reason and abort beam search
            if result.outputs[0].finish_reason == "error":
                # yield error output and terminate beam search
                yield RequestOutput(
                    request_id=request_id,
                    prompt=prompt_text,
                    outputs=[
                        CompletionOutput(
                            index=0,
                            text="",
                            token_ids=[],
                            cumulative_logprob=None,
                            logprobs=None,
                            finish_reason="error",
                        )
                    ],
                    finished=True,
                    prompt_token_ids=prompt_token_ids,
                    prompt_logprobs=None,
                )
                return

            if result.outputs[0].logprobs is not None:
                logprobs = result.outputs[0].logprobs[0]
                all_beams_token_id.extend(list(logprobs.keys()))
                all_beams_logprob.extend(
                    [
                        current_beam.cum_logprob + obj.logprob
                        for obj in logprobs.values()
                    ]
                )

        # Handle the token for the end of sentence (EOS)
        all_beams_token_id = np.array(all_beams_token_id)
        all_beams_logprob = np.array(all_beams_logprob)

        if not ignore_eos:
            # Get the index position of eos token in all generated results
            eos_idx = np.where(all_beams_token_id == eos_token_id)[0]
            for idx in eos_idx:
                current_beam = all_beams[idx // logprobs_num]
                result = output[idx // logprobs_num]
                assert result.outputs[0].logprobs is not None
                logprobs_entry = result.outputs[0].logprobs[0]
                completed.append(
                    BeamSearchSequence(
                        orig_prompt=prompt,
                        tokens=current_beam.tokens + [eos_token_id]
                        if include_stop_str_in_output
                        else current_beam.tokens,
                        logprobs=current_beam.logprobs + [logprobs_entry],
                        cum_logprob=float(all_beams_logprob[idx]),
                        finish_reason="stop",
                        stop_reason=eos_token_id,
                    )
                )
            # After processing, set the log probability of the eos condition
            # to negative infinity.
            all_beams_logprob[eos_idx] = -np.inf

        # Processing non-EOS tokens
        # Get indices of the top beam_width probabilities
        topn_idx = np.argpartition(np.negative(all_beams_logprob), beam_width)[
            :beam_width
        ]

        # Apply cumulative threshold filtering (BeamStar)
        BEAM_STAR_FILTERING = True
        if BEAM_STAR_FILTERING:
            learn_threshold = True
            # NOTE: parenthesized correctly -- without the parens, `or` binds
            # looser than `and`, so `cum_threshold is not None` (almost always
            # true) short-circuits the whole condition and the "don't filter
            # the last step" rule never applies.
            if token < max_tokens - 1 and (token not in _EXPLORATION_TOKENS):
                if (cum_threshold is not None or learn_threshold):
                    top_beams_logprob = all_beams_logprob[topn_idx]

                    # Mask out non-finite entries (-inf from EOS beams that
                    # landed in the top-beam_width partition) BEFORE they reach
                    # the running stats or the ledger. Left unmasked, a single
                    # -inf poisons std/max_val for this (token) bucket for every
                    # subsequent request that shares it, and can turn the
                    # logsumexp in the ledger into nan.
                    finite = np.isfinite(top_beams_logprob)
                    if not finite.all():
                        topn_idx = topn_idx[finite]
                        top_beams_logprob = top_beams_logprob[finite]
                        
                    if learn_threshold:                        
                        if is_global_stats:
                            self.req_stats[token].push(top_beams_logprob)
                            stats = self.req_stats[token]
                            thr = stats.max -  2 * (token+1) * stats.std

                        else:
                            self.req_stats[token].push(top_beams_logprob - top_beams_logprob.max())
                            stats = self.req_stats[token]
                            # rms = sqrt(stats.mean**2 + stats.std**2)   # spread about the anchor (d=0)
                            # thr = top_beams_logprob.max() - 3.5 * self.req_stats[token].std_within
                            thr = top_beams_logprob.max() -  (stats.std_within * sqrt(token+1) + (token+1) + 0.25)/sqrt(2)  # threshold based on max_val and
                    else:
                        # self.req_stats[token].push(top_beams_logprob)
                        #                         stats = self.req_stats[token]
                        #                         # rms = sqrt(stats.mean**2 + stats.std**2)   # spread about the anchor (d=0)
                        #                         thr = stats.max -  2 * (token+1) * stats.std  # threshold based on max_val and
                        thr = self.thr[token]  # use fixed threshold values for now, can be tuned or learned based on stats

                    keep_pos = np.flatnonzero(top_beams_logprob >= thr)

                    if keep_pos.size == 0:
                        # Fallback: keep the single best candidate to guarantee
                        # progress. Must use argmax, not a fixed index -- the
                        # order of `topn_idx` (from argpartition) is unspecified,
                        # so index 0 is not necessarily the highest-scoring beam.
                        keep_pos = np.array([np.argmax(top_beams_logprob)], dtype=np.intp)

                    # Charge the rate-distortion ledger AFTER the fallback is
                    # resolved, so it always receives a non-empty keep_pos.
                    keep_pos = ledger.step(top_beams_logprob, keep_pos, token)

                    logger.debug("token %d: num_kept %d", token, keep_pos.size)

                    if DEBUG:
                        # Log the running stats for this token index
                        # stats = self.req_stats[token]
                        # logger.debug(
                        #     "token %d: mean=%.4f, std=%.4f, rms=%.4f, threshold=%.4f",
                        #     token,
                        #     stats.mean,
                        #     stats.std,
                        #     sqrt(stats.mean**2 + stats.std**2),
                        #     thr,
                        # )
                    # ── per-token JSONL log ──────────────────────────────
                        json.dump({
                            "type": "token",
                            "request_id": request_id,
                            "token": token,
                            "num_kept": int(keep_pos.size),
                            "std": float(self.req_stats[token].std_within),
                            "thr": float(thr),
                        }, log_f)
                        log_f.write("\n")

                    topn_idx = topn_idx[keep_pos]

        for idx in topn_idx:
            current_beam = all_beams[idx // logprobs_num]
            result = output[idx // logprobs_num]
            token_id = int(all_beams_token_id[idx])
            assert result.outputs[0].logprobs is not None
            logprobs_entry = result.outputs[0].logprobs[0]
            new_beams.append(
                BeamSearchSequence(
                    orig_prompt=prompt,
                    tokens=current_beam.tokens + [token_id],
                    logprobs=current_beam.logprobs + [logprobs_entry],
                    lora_request=current_beam.lora_request,
                    cum_logprob=float(all_beams_logprob[idx]),
                )
            )

        all_beams = new_beams

    if DEBUG:
        # ── final RD summary JSONL log ──────────────────────────────────────
        rd = ledger.summary()
        json.dump({
            "type": "summary",
            "request_id": request_id,
            "rd_summary": rd,
        }, log_f)
        log_f.write("\n")
        log_f.close()

        logger.debug("beam_search request %s: rd_summary=%s", request_id, rd)

    completed.extend(all_beams)
    sorted_completed = sorted(completed, key=sort_beams_key, reverse=True)
    best_beams = sorted_completed[:beam_width]

    for beam in best_beams:
        if beam.tokens[-1] == eos_token_id and not ignore_eos:
            # Skip the eos token in the text.
            tokens = beam.tokens[tokenized_length:-1]
        else:
            tokens = beam.tokens[tokenized_length:]
        beam.text = tokenizer.decode(tokens)

    # Final, complete-run ledger -- computed once, after the decoding loop,
    # not per-token. Attach/log it here so the summary reflects the whole
    # request rather than a partial, still-growing snapshot.
    rd = ledger.summary()
    logger.debug("beam_search request %s: rd_summary=%s", request_id, rd)

    yield RequestOutput(
        request_id=request_id,
        prompt=prompt_text,
        outputs=[
            CompletionOutput(
                text=beam.text,  # type: ignore
                cumulative_logprob=beam.cum_logprob,
                token_ids=beam.tokens[tokenized_length:],
                index=i,
                logprobs=beam.logprobs,
                finish_reason=beam.finish_reason
                if beam.finish_reason is not None
                else "length",
                stop_reason=beam.stop_reason,
            )
            for (i, beam) in enumerate(best_beams)
        ],
        finished=True,
        prompt_token_ids=prompt_token_ids,
        prompt_logprobs=None,
    )
